### ISSUE TITLE
Crash on hand-off from bootmgr.exe to kernel.exe

### ISSUE THREAD

**Issue by ilmmatias** [yuuma03/palladium#1]
Currently, the kernel loads up properly on QEMU (with KVM) and VirtualBox, but it crashes (triple fault) on real hardware.
The crash seems to happen on transfer.asm, right after we set RSP and try jumping to the kernel entry point.
As we do reach the 64-bits entry (and then crash when jumping into the kernel), this might be a problem with the paging structures?

**Comment by ilmmatias** [comment]
0457f7a seems to fix the problem in two of the test machines, but it still crashes on a Ryzen 3400G rig.

**Comment by belliash** [comment]
When an exception occurs, CPU invokes the exception handler. If it cannot do that, it raises another exception (double fault) which it tries to handle with another exception handler and when it fails, it leads to triple fault and then system hangs or reboots. Setup GDT and IDT, then you will know what was your first exception.

**Comment by ilmmatias** [comment]
After all changes, the problem seems to very rarely happen now, and looking at QEMU, the memory doesn't get mapped properly when it happens, probably KASLR related?
